export const SIGNIN_USER = 'SIGNIN_USER',
             AUTH_USER = 'AUTH_USER',
             UNAUTH_USER = 'UNAUTH_USER',
             AUTH_ERROR = 'AUTH_ERROR',
             FETCH_MESSAGE = 'FETCH_MESSAGE',
             FETCH_PLAYERS = 'FETCH_PLAYERS',
             FETCH_BOXSCORES = 'FETCH_BOXSCORES',
             FETCH_BOXSCORE_TEAM_PLAYER_INFO = 'FETCH_BOXSCORE_TEAM_PLAYER_INFO',
             FETCH_ERROR = 'FETCH_ERROR',
             FETCH_PLAYER = 'FETCH_PLAYER',
             FETCH_TEAMS = 'FETCH_TEAMS',
             FETCH_STANDINGS = 'FETCH_STANDINGS',
             FETCH_REG_SEASON_PLAYER_STATS = 'FETCH_REG_SEASON_PLAYER_STATS',
             FETCH_CAREER_REG_SEASON_PLAYER_STATS = 'FETCH_CAREER_REG_SEASON_PLAYER_STATS',
             FETCH_TANKATHON = 'FETCH_TANKATHON';














/* END */
